<?php
$data = array (
  0 => 
  array (
    'cat_id' => '46',
    'cat_name' => '墙画',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '1480741834.jpg',
    'goods_num' => 108,
  ),
  1 => 
  array (
    'cat_id' => '48',
    'cat_name' => '软包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 12,
  ),
  2 => 
  array (
    'cat_id' => '51',
    'cat_name' => '辅料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'type_img' => '',
    'goods_num' => 8,
  ),
  3 => 
  array (
    'cat_id' => '161',
    'cat_name' => '装饰画',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '43',
    'cat_name' => '窗帘',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 177,
  ),
  5 => 
  array (
    'cat_id' => '45',
    'cat_name' => '墙纸',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 706,
  ),
  6 => 
  array (
    'cat_id' => '47',
    'cat_name' => '无缝墙布',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 30,
  ),
  7 => 
  array (
    'cat_id' => '50',
    'cat_name' => '硅藻泥',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'type_img' => '',
    'goods_num' => 16,
  ),
  8 => 
  array (
    'cat_id' => '44',
    'cat_name' => '风格分类',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'type_img' => '',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '53',
    'cat_name' => '场所分类',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'type_img' => '',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '52',
    'cat_name' => '材质分类',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'type_img' => '',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '172',
    'cat_name' => '田园风格',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '173',
    'cat_name' => '欧式风格',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '62',
    'cat_name' => '中式风格',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755565.jpg',
    'goods_num' => 61,
  ),
  14 => 
  array (
    'cat_id' => '174',
    'cat_name' => '现代风格',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '67',
    'cat_name' => '场所分类',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'type_img' => '',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '69',
    'cat_name' => '风格分类',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'type_img' => '',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '68',
    'cat_name' => '材质分类',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'type_img' => '',
    'goods_num' => 73,
  ),
  18 => 
  array (
    'cat_id' => '94',
    'cat_name' => '场所分类',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'type_img' => '',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '114',
    'cat_name' => '风格分类',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'type_img' => '',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '95',
    'cat_name' => '材质分类',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '97',
    'cat_name' => '风格分类',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'type_img' => '',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '96',
    'cat_name' => '场所分类',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'type_img' => '',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '116',
    'cat_name' => '材质分类',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'type_img' => '1480747320.jpg',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '147',
    'cat_name' => '级别分类',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'type_img' => '',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '165',
    'cat_name' => '品种分类',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '126',
    'cat_name' => '品种分类',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '1480747154.jpg',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '122',
    'cat_name' => '基膜',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '121',
    'cat_name' => '防霉剂除霉剂',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489560419.jpg',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '123',
    'cat_name' => '盒装糯米胶',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '125',
    'cat_name' => '袋装糯米胶',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '66',
    'cat_name' => '棉麻、纱',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755245.jpg',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '55',
    'cat_name' => '卧室',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755478.jpg',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '57',
    'cat_name' => '儿童房',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755387.jpg',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '59',
    'cat_name' => '娱乐会所',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755302.jpg',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '54',
    'cat_name' => '客厅',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755427.jpg',
    'goods_num' => 62,
  ),
  36 => 
  array (
    'cat_id' => '56',
    'cat_name' => '书房',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755363.jpg',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '58',
    'cat_name' => '餐厅',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755454.jpg',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '83',
    'cat_name' => '餐厅',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558986.jpg',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '79',
    'cat_name' => '客厅',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480677900.jpg',
    'goods_num' => 1287,
  ),
  40 => 
  array (
    'cat_id' => '81',
    'cat_name' => '书房',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558928.jpg',
    'goods_num' => 177,
  ),
  41 => 
  array (
    'cat_id' => '84',
    'cat_name' => '娱乐场所',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558866.jpg',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '163',
    'cat_name' => '婚房',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559192.jpg',
    'goods_num' => 4,
  ),
  43 => 
  array (
    'cat_id' => '80',
    'cat_name' => '卧室',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558907.jpg',
    'goods_num' => 940,
  ),
  44 => 
  array (
    'cat_id' => '82',
    'cat_name' => '儿童房',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558971.jpg',
    'goods_num' => 230,
  ),
  45 => 
  array (
    'cat_id' => '85',
    'cat_name' => '无纺',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489556863.jpg',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '87',
    'cat_name' => 'PVC',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557181.jpg',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '89',
    'cat_name' => '石英壁布',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557466.jpg',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '91',
    'cat_name' => '蚕丝',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557872.jpg',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '93',
    'cat_name' => '草编',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558099.jpg',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '164',
    'cat_name' => '无纺纯',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558290.jpg',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '86',
    'cat_name' => '纯纸',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557044.jpg',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '88',
    'cat_name' => '纱线',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557363.jpg',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '90',
    'cat_name' => '金箔纸',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557737.jpg',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '92',
    'cat_name' => '芬兰纸',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557928.jpg',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '71',
    'cat_name' => '欧式风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489555563.jpg',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '73',
    'cat_name' => '美式风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489555947.jpg',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '75',
    'cat_name' => '背景墙',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558441.jpg',
    'goods_num' => 299,
  ),
  58 => 
  array (
    'cat_id' => '77',
    'cat_name' => '高端',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489556521.jpg',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '70',
    'cat_name' => '田园风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489555360.jpg',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '72',
    'cat_name' => '中式风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489555765.jpg',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '74',
    'cat_name' => '现代风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489556171.jpg',
    'goods_num' => 407,
  ),
  62 => 
  array (
    'cat_id' => '76',
    'cat_name' => '儿童风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489556282.jpg',
    'goods_num' => 136,
  ),
  63 => 
  array (
    'cat_id' => '78',
    'cat_name' => '进口',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489556672.jpg',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '145',
    'cat_name' => '卧室',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559381.jpg',
    'goods_num' => '4',
  ),
  65 => 
  array (
    'cat_id' => '107',
    'cat_name' => '客厅',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749999.jpg',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '109',
    'cat_name' => '书房',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480750522.jpg',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '111',
    'cat_name' => '餐厅',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480750030.jpg',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '108',
    'cat_name' => '卧室',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480750056.jpg',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '110',
    'cat_name' => '儿童房',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480750475.jpg',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '112',
    'cat_name' => '娱乐会所',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480750088.jpg',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '99',
    'cat_name' => '欧式风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749885.jpg',
    'goods_num' => 22,
  ),
  72 => 
  array (
    'cat_id' => '101',
    'cat_name' => '美式风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749637.jpg',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '103',
    'cat_name' => '背景墙',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749544.jpg',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '105',
    'cat_name' => '高端',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749710.jpg',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '98',
    'cat_name' => '田园风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749672.jpg',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '100',
    'cat_name' => '中式风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749464.jpg',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '102',
    'cat_name' => '现代风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749746.jpg',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '104',
    'cat_name' => '儿童风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749591.jpg',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '106',
    'cat_name' => '进口',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '151',
    'cat_name' => '田园风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744700.jpg',
    'goods_num' => 75,
  ),
  81 => 
  array (
    'cat_id' => '152',
    'cat_name' => '欧式风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744516.jpg',
    'goods_num' => 106,
  ),
  82 => 
  array (
    'cat_id' => '154',
    'cat_name' => '美式风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744739.jpg',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '156',
    'cat_name' => '儿童风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744535.jpg',
    'goods_num' => 18,
  ),
  84 => 
  array (
    'cat_id' => '153',
    'cat_name' => '中式风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744627.jpg',
    'goods_num' => 90,
  ),
  85 => 
  array (
    'cat_id' => '155',
    'cat_name' => '现代风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744438.jpg',
    'goods_num' => 54,
  ),
  86 => 
  array (
    'cat_id' => '128',
    'cat_name' => '人造革',
    'measure_unit' => '',
    'parent_id' => '116',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480747348.jpg',
    'goods_num' => 10,
  ),
  87 => 
  array (
    'cat_id' => '171',
    'cat_name' => '渗透性基膜',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489562981.jpg',
    'goods_num' => 0,
  ),
  88 => 
  array (
    'cat_id' => '170',
    'cat_name' => '高端',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489560094.jpg',
    'goods_num' => 0,
  ),
  89 => 
  array (
    'cat_id' => '168',
    'cat_name' => '高端',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489560008.jpg',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '169',
    'cat_name' => '中高端',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489563618.jpg',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '162',
    'cat_name' => '硅藻泥',
    'measure_unit' => '',
    'parent_id' => '126',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559836.jpg',
    'goods_num' => 7,
  ),
  92 => 
  array (
    'cat_id' => '127',
    'cat_name' => '灰泥',
    'measure_unit' => '',
    'parent_id' => '126',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559854.jpg',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '149',
    'cat_name' => '中端',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480747462.jpg',
    'goods_num' => 0,
  ),
  94 => 
  array (
    'cat_id' => '167',
    'cat_name' => '硬包',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559649.jpg',
    'goods_num' => 13,
  ),
  95 => 
  array (
    'cat_id' => '166',
    'cat_name' => '软包',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559626.jpg',
    'goods_num' => 0,
  ),
);
?>