<?php
$data = array (
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '墙画',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '1480741834.jpg',
    'goods_num' => 108,
    'level' => 0,
    'id' => '46',
    'name' => '墙画',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '场所分类',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '94',
    'name' => '场所分类',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => '卧室',
    'measure_unit' => '',
    'parent_id' => '94',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559381.jpg',
    'goods_num' => '4',
    'level' => 2,
    'id' => '145',
    'name' => '卧室',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '风格分类',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '114',
    'name' => '风格分类',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '田园风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744700.jpg',
    'goods_num' => 75,
    'level' => 2,
    'id' => '151',
    'name' => '田园风格',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '欧式风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744516.jpg',
    'goods_num' => 106,
    'level' => 2,
    'id' => '152',
    'name' => '欧式风格',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => '美式风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744739.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '154',
    'name' => '美式风格',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => '儿童风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744535.jpg',
    'goods_num' => 18,
    'level' => 2,
    'id' => '156',
    'name' => '儿童风格',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => '中式风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744627.jpg',
    'goods_num' => 90,
    'level' => 2,
    'id' => '153',
    'name' => '中式风格',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => '现代风格',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480744438.jpg',
    'goods_num' => 54,
    'level' => 2,
    'id' => '155',
    'name' => '现代风格',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '软包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 12,
    'level' => 0,
    'id' => '48',
    'name' => '软包',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '材质分类',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'type_img' => '1480747320.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '116',
    'name' => '材质分类',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '人造革',
    'measure_unit' => '',
    'parent_id' => '116',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480747348.jpg',
    'goods_num' => 10,
    'level' => 2,
    'id' => '128',
    'name' => '人造革',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => '级别分类',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '147',
    'name' => '级别分类',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '中端',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480747462.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '149',
    'name' => '中端',
  ),
  165 => 
  array (
    'cat_id' => '165',
    'cat_name' => '品种分类',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '165',
    'name' => '品种分类',
  ),
  167 => 
  array (
    'cat_id' => '167',
    'cat_name' => '硬包',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559649.jpg',
    'goods_num' => 13,
    'level' => 2,
    'id' => '167',
    'name' => '硬包',
  ),
  166 => 
  array (
    'cat_id' => '166',
    'cat_name' => '软包',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559626.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '166',
    'name' => '软包',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '辅料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'type_img' => '',
    'goods_num' => 8,
    'level' => 0,
    'id' => '51',
    'name' => '辅料',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '基膜',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '122',
    'name' => '基膜',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => '渗透性基膜',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489562981.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '171',
    'name' => '渗透性基膜',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => '高端',
    'measure_unit' => '',
    'parent_id' => '122',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489560094.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '170',
    'name' => '高端',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '防霉剂除霉剂',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489560419.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '121',
    'name' => '防霉剂除霉剂',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '盒装糯米胶',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '123',
    'name' => '盒装糯米胶',
  ),
  168 => 
  array (
    'cat_id' => '168',
    'cat_name' => '高端',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489560008.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '168',
    'name' => '高端',
  ),
  169 => 
  array (
    'cat_id' => '169',
    'cat_name' => '中高端',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489563618.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '169',
    'name' => '中高端',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '袋装糯米胶',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '125',
    'name' => '袋装糯米胶',
  ),
  161 => 
  array (
    'cat_id' => '161',
    'cat_name' => '装饰画',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 0,
    'id' => '161',
    'name' => '装饰画',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '窗帘',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 177,
    'level' => 0,
    'id' => '43',
    'name' => '窗帘',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '风格分类',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => '风格分类',
  ),
  172 => 
  array (
    'cat_id' => '172',
    'cat_name' => '田园风格',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 2,
    'id' => '172',
    'name' => '田园风格',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => '欧式风格',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 2,
    'id' => '173',
    'name' => '欧式风格',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '中式风格',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755565.jpg',
    'goods_num' => 61,
    'level' => 2,
    'id' => '62',
    'name' => '中式风格',
  ),
  174 => 
  array (
    'cat_id' => '174',
    'cat_name' => '现代风格',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 2,
    'id' => '174',
    'name' => '现代风格',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '场所分类',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '53',
    'name' => '场所分类',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '卧室',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755478.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '55',
    'name' => '卧室',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '儿童房',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755387.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '57',
    'name' => '儿童房',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '娱乐会所',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755302.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '59',
    'name' => '娱乐会所',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '客厅',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755427.jpg',
    'goods_num' => 62,
    'level' => 2,
    'id' => '54',
    'name' => '客厅',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '书房',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755363.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '56',
    'name' => '书房',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '餐厅',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755454.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '58',
    'name' => '餐厅',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '材质分类',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '材质分类',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '棉麻、纱',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480755245.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '66',
    'name' => '棉麻、纱',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '墙纸',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 706,
    'level' => 0,
    'id' => '45',
    'name' => '墙纸',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '场所分类',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '67',
    'name' => '场所分类',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '书房',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558928.jpg',
    'goods_num' => 177,
    'level' => 2,
    'id' => '81',
    'name' => '书房',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '餐厅',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558986.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '83',
    'name' => '餐厅',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '客厅',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480677900.jpg',
    'goods_num' => 1287,
    'level' => 2,
    'id' => '79',
    'name' => '客厅',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '儿童房',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558971.jpg',
    'goods_num' => 230,
    'level' => 2,
    'id' => '82',
    'name' => '儿童房',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '娱乐场所',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558866.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => '娱乐场所',
  ),
  163 => 
  array (
    'cat_id' => '163',
    'cat_name' => '婚房',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559192.jpg',
    'goods_num' => 4,
    'level' => 2,
    'id' => '163',
    'name' => '婚房',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '卧室',
    'measure_unit' => '',
    'parent_id' => '67',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558907.jpg',
    'goods_num' => 942,
    'level' => 2,
    'id' => '80',
    'name' => '卧室',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '风格分类',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '69',
    'name' => '风格分类',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '欧式风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489555563.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '71',
    'name' => '欧式风格',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '美式风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489555947.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => '美式风格',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '背景墙',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558441.jpg',
    'goods_num' => 299,
    'level' => 2,
    'id' => '75',
    'name' => '背景墙',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '高端',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489556521.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '高端',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '田园风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489555360.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '田园风格',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '中式风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489555765.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '72',
    'name' => '中式风格',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '现代风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489556171.jpg',
    'goods_num' => 407,
    'level' => 2,
    'id' => '74',
    'name' => '现代风格',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '儿童风格',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489556282.jpg',
    'goods_num' => 136,
    'level' => 2,
    'id' => '76',
    'name' => '儿童风格',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '进口',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489556672.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '78',
    'name' => '进口',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '材质分类',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'type_img' => '',
    'goods_num' => 73,
    'level' => 1,
    'id' => '68',
    'name' => '材质分类',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '无纺',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489556863.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '85',
    'name' => '无纺',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => 'PVC',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557181.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '87',
    'name' => 'PVC',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '石英壁布',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557466.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '89',
    'name' => '石英壁布',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '蚕丝',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557872.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '91',
    'name' => '蚕丝',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '草编',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558099.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '93',
    'name' => '草编',
  ),
  164 => 
  array (
    'cat_id' => '164',
    'cat_name' => '无纺纯',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489558290.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '164',
    'name' => '无纺纯',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '纯纸',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557044.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '86',
    'name' => '纯纸',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '纱线',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557363.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '88',
    'name' => '纱线',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '金箔纸',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557737.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '90',
    'name' => '金箔纸',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '芬兰纸',
    'measure_unit' => '',
    'parent_id' => '68',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489557928.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '92',
    'name' => '芬兰纸',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '无缝墙布',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'type_img' => '',
    'goods_num' => 30,
    'level' => 0,
    'id' => '47',
    'name' => '无缝墙布',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '材质分类',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '95',
    'name' => '材质分类',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '风格分类',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '97',
    'name' => '风格分类',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '欧式风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749885.jpg',
    'goods_num' => 22,
    'level' => 2,
    'id' => '99',
    'name' => '欧式风格',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '美式风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749637.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '101',
    'name' => '美式风格',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '背景墙',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749544.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '背景墙',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '高端',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749710.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '105',
    'name' => '高端',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '田园风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749672.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '田园风格',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '中式风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749464.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '100',
    'name' => '中式风格',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '现代风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749746.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '现代风格',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '儿童风格',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749591.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '儿童风格',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '进口',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '进口',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '场所分类',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'type_img' => '',
    'goods_num' => 0,
    'level' => 1,
    'id' => '96',
    'name' => '场所分类',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '客厅',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480749999.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '客厅',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '书房',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480750522.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '109',
    'name' => '书房',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '餐厅',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480750030.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '111',
    'name' => '餐厅',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '卧室',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480750056.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '卧室',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '儿童房',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480750475.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '110',
    'name' => '儿童房',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '娱乐会所',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1480750088.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '112',
    'name' => '娱乐会所',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '硅藻泥',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'type_img' => '',
    'goods_num' => 16,
    'level' => 0,
    'id' => '50',
    'name' => '硅藻泥',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '品种分类',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'type_img' => '1480747154.jpg',
    'goods_num' => 0,
    'level' => 1,
    'id' => '126',
    'name' => '品种分类',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => '硅藻泥',
    'measure_unit' => '',
    'parent_id' => '126',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559836.jpg',
    'goods_num' => 7,
    'level' => 2,
    'id' => '162',
    'name' => '硅藻泥',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '灰泥',
    'measure_unit' => '',
    'parent_id' => '126',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'type_img' => '1489559854.jpg',
    'goods_num' => 0,
    'level' => 2,
    'id' => '127',
    'name' => '灰泥',
  ),
);
?>